### ISSUE TITLE
npm run chatgpt 运行报错，香港腾讯云服务器

### ISSUE THREAD

**Issue by Hkaisense** [sunshanpeng/wechaty-chatgpt#10]
GError: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.start (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:375:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:361:12)
    at GrpcManager.start (file:///root/wechaty-chatgpt/node_modules/wechaty-puppet-service/dist/esm/src/client/grpc-manager.js:128:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetService.onStart (file:///root/wechaty-chatgpt/node_modules/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:110:9)
    at async PuppetService.start (file:///root/wechaty-chatgpt/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)
    at async PuppetService.start (file:///root/wechaty-chatgpt/node_modules/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13) {
  code: 14,
  details: 'No connection established'
}

**Comment by Hkaisense** [comment]
重装node,依赖包等 解决
